### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by connyduck** [Kentico/kontent-java-packages#130]
Please publish the libraries on Maven Central or another repository that is not JCenter.
JCenter is being shut down and will stop working on May 1st 2021.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Simply007** [comment]
Hello @connyduck,

thanks for the heads-up! That is really sudden...

I have looked around the alternative services and I have found these that might be sufficient to use:
* https://jfrog.com/artifactory
* https://jitpack.io

Could you comment on these above or any other service you would recommend to migrate to?

**Comment by Simply007** [comment]
+ If you have any resource that would help with the migration please share it here as well.

**Comment by Simply007** [comment]
Notes:
* https://jeroenmols.com/blog/2021/02/04/migratingjcenter/
* https://central.sonatype.org/pages/gradle.html

**Comment by Simply007** [comment]
Bintray blog post update:

> UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.
>
> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

**Comment by Simply007** [comment]
Android Plugin replacement: https://stackoverflow.com/a/66168622/3529135

**Comment by Simply007** [comment]
Hello @connyduck - I have released [v 4.4.1](https://repo1.maven.org/maven2/com/github/kentico/kontent-delivery/4.4.1/) on Maven Central. 

The referenced pull request #131 will be verified by one of my colleagues but still, could you test out the new version as well? There should be no functional changes.

**Comment by connyduck** [comment]
Yes, it works, 4.4.1 is downloaded from Maven Central. Thank you!
