### ISSUE TITLE
Response Faking

### ISSUE THREAD

**Issue by smithaaron** [Kentico/kontent-java-packages#138]
### Expected result

There's a link in the wiki to 'Faking responses for unit testing`, however there is no corresponding page. Are there any guidelines or examples available for unit testing?

### Resources
https://github.com/Kentico/kontent-java-packages/wiki

**Comment by Simply007** [comment]
Hello @smithaaron,

I will try to dig and place the wiki page back. 

Until then, you could use the tests source code to mock the responses using `org.apache.http.localserver.LocalServerTestBase`:

https://github.com/Kentico/kontent-java-packages/blob/master/kontent-delivery/src/test/java/kentico/kontent/delivery/DeliveryClientTest.java#L287-L326

```java
this.serverBootstrap.registerHandler(
        String.format("/%s/%s", projectId, "items/on_roasts"),
        (request, response, context) -> {
        
            response.setEntity(
                    new InputStreamEntity(
                            this.getClass().getResourceAsStream("SampleContentItem.json")
                    )
            );
        });
```

**Comment by Simply007** [comment]
Hello @smithaaron,

I went through the history of the wiki, but the page was never created.

I browsed the code and filled the Faking response page. I also suggested an alternative way of faking responses, which is implemented right in the client.

If you spot any problem or issue, feel free to re-open this issue.
