### ISSUE TITLE
Missing documentation on Rich Text Rendering

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-java-packages#60]
### Motivation

Rendering of rich text elements is a significantly more complex process than that of the ordinary plan text elements. Also, it can be approached in two distinct ways--by writing imperative code to render the rich text content, or by using a templating engine of some sort. One might not grasp the pros and cons of those two approaches at first.

### Guidelines

Document how to render contents of rich text elements.

- https://github.com/Kentico/delivery-sdk-java/wiki/Rich-text-rendering

Similarly to:
- https://github.com/Kentico/delivery-sdk-net/wiki/String-based-rendering-of-items-in-Rich-text
- or https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering

**Comment by aweigold** [comment]
This would be a good idea to start after #62 and #61

**Comment by rjseymour66** [comment]
I am a professional technical writer - do you still need help with these docs?  If so, I would be more than happy to help!

**Comment by aweigold** [comment]
@rjseymour66  Definitely would love the help!

I am going through the process right now of some big changes for the next major version release.  Might make most sense to work on documentation when that is complete or near complete.  Care if I reach out to you then?

**Comment by rjseymour66** [comment]
Absolutely - do you have any sort of timeframe?

**Comment by aweigold** [comment]
Within the next month.

**Comment by rjseymour66** [comment]
Sounds good - I'll keep my eyes peeled.

**Comment by Simply007** [comment]
The string-based resolution is described here: https://github.com/Kentico/kontent-java-packages/wiki/Rich-text-resolution#completely-custom-template-configuration-ie-default-fallback-rich-text-element-resolver

The strongly-typed resolution/mapping part will be covered in #125
