### ISSUE TITLE
Empty content in Rich Text

### ISSUE THREAD

**Issue by zbynekh** [Kentico/kontent-java-packages#93]
Hey community!
We are now considering some changes in handling default empty value in Rich Text element. For now the empty value returned by Kontent Delivery equals to empty paragraph (`<p><br/><p>`). How Java SDK will be affected if the empty value would be empty string? Could this be the breaking change for the SDK?

**Comment by Simply007** [comment]
@aweigold - could you take a quick look?

**Comment by Simply007** [comment]
I would recommend adding a test to [DeliveryClientTest.java](https://github.com/Kentico/kontent-java-packages/blob/master/kontent-delivery/src/test/java/kentico/kontent/delivery/DeliveryClientTest.java) witch mocked empty rich text element as was done i.e. in PHP Kontent delivery SDK: https://github.com/Kentico/kontent-delivery-sdk-php/pull/88
